name: Cl

on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
       python-version: '3.6'
       architecture: 'x64'
    - run: pip install -r requirements.txt
    - run: python in.py
